name: Build and Deploy Staging
on:
  push:
    branches:
      - develop

env:
  PATHS: "/*"
  SOURCE_DIR: "./build"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  REACT_APP_HEREMAPS_API_KEY: ${{ secrets.HEREMAPS_API_KEY }}
  PUBLIC_URL: ${{ secrets.PUBLIC_URL_STAGING }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_STAGING }}
  DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID_STAGING }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: "."
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install Dependencies
        working-directory: ${{env.working-directory}}
        run: yarn install --frozen-lockfile

      - name: Lint
        working-directory: ${{env.working-directory}}
        run: yarn run lint

      - name: Build
        working-directory: ${{env.working-directory}}
        run: yarn run build

      - name: Deploy to S3 Staging
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete

      - name: Invalidate Cloudfront Staging
        uses: muratiger/invalidate-cloudfront-and-wait-for-completion-action@master
